module.exports = {
  name: 'observability-evolution',
  title: 'The Evolution of Observability — Elastic',
  slidesDir: 'slides',
  slides: [
    'cover.html',
    'agenda.html',
    'history-monitoring.html',
    'volume-problem.html',
    'three-pillars.html',
    'beyond-pillars.html',
    'standardization.html',
    'ai-observability.html',
    'competitive-landscape.html',
    'elastic-differentiators.html',
    'closing.html',
  ],
  labels: [
    'Cover',
    'Agenda',
    'History & Evolution',
    'The Volume Problem',
    'The Three Pillars',
    'Beyond the Pillars',
    'Standards & Unification',
    'AI-Driven Observability',
    'Competitive Landscape',
    'Elastic Differentiators',
    'Key Takeaways',
  ],
};
